# Generated by Django 4.0.2 on 2022-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='date',
            field=models.CharField(max_length=30, verbose_name='date'),
        ),
    ]
