# Generated by Django 4.0.2 on 2022-03-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('number', models.CharField(max_length=20, verbose_name='number')),
                ('full_address', models.CharField(max_length=255, verbose_name='full_address')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('img', models.ImageField(upload_to='', verbose_name='img')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
    ]
