# Generated by Django 4.0.2 on 2022-04-01 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_teampositionmodel_teammodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='position',
        ),
        migrations.AddField(
            model_name='teammodel',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='pages.teampositionmodel', verbose_name='position'),
        ),
    ]
