# Generated by Django 4.0.2 on 2022-04-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_teammodel_position_teammodel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='pages.teampositionmodel', verbose_name='position'),
            preserve_default=False,
        ),
    ]
