# Generated by Django 4.0.2 on 2022-04-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_faqsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('full_name', models.CharField(max_length=50, verbose_name='full_name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('messege', models.TextField(verbose_name='messege')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
        ),
    ]
