# Generated by Django 4.0.2 on 2022-04-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_bookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebannermodel',
            name='background',
            field=models.ImageField(upload_to='banner/', verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='img',
            field=models.ImageField(upload_to='filial/', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='photo',
            field=models.ImageField(upload_to='team/', verbose_name='photo'),
        ),
    ]
