# Generated by Django 4.0.2 on 2022-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_homebannermodel_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='messege',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='message',
            field=models.TextField(default=12, verbose_name='message'),
            preserve_default=False,
        ),
    ]
