# Generated by Django 4.0.2 on 2022-05-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_bookingmodel_messege_bookingmodel_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('image', models.ImageField(upload_to='gallary/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
            },
        ),
    ]
