# Generated by Django 4.0.2 on 2022-04-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_commentmodel_phone_alter_authormodel_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='blog.IpModel'),
        ),
    ]
